export const sagaActions ={
    FETCH_INIT_CATEGORY:'FETCH_INIT_CATEGORY' , 
    FETCH_PAGE_CATEGORY :'FETCH_PAGE_CATEGORY',
    SEARCH_CATEGORY :'SEARCH_CATEGORY',
    FETCH_IMAGES_PAGE :'FETCH_IMAGES_PAGE',
    SEARCH_IMAGES :'SEARCH_IMAGES' , 
    FETCH_ONE_IMAGE:'FETCH_ONE_IMAGE',
    FETCH_CATEGORY_ERROR : 'FETCH_CATEGORY_ERROR' , 
    FETCH_IMAGE_ERROR :'FETCH_IMAGE_ERROR',
}