export const sagaActions ={
    FETCH_CATEGORY:'FETCH_CATEGORY' , 
    FETCH_IMAGES :'FETCH_IMAGES',
    SEARCH_IMAGES :'SEARCH_IMAGES' , 
    FETCH_CATEGORY_ERROR : 'FETCH_CATEGORY_ERROR' , 
    FETCH_IMAGE_ERROR :'FETCH_IMAGE_ERROR'
}